name: Convertly Type Check CI

on:
  push:
    branches: ["main"]
    paths: ["*.py"]
  pull_request:
    branches: ["main"]
    paths: ["*.py"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Install Poetry
      run: pipx install poetry

    - name: Set up Python 3.12
      uses: actions/setup-python@v6
      with:
        python-version: "3.12"
        cache: poetry

    - name: Install dependencies
      run: poetry install

    - name: Run mypy
      run: poetry run mypy --platform win32 src
